------------------------------------------------------------------------
-- Clinical Trial Operations: Database & Schema Setup
-- Run as ACCOUNTADMIN
------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS HEALTHCARE_CLINICAL_TRIALS;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLINICAL_TRIALS.RAW;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLINICAL_TRIALS.CURATED;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLINICAL_TRIALS.AI;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLINICAL_TRIALS.ML;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLINICAL_TRIALS.SEARCH;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLINICAL_TRIALS.APP;
