------------------------------------------------------------------------
-- Clinical Trial Operations: Curated Layer (Dynamic Tables)
------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;
USE DATABASE HEALTHCARE_CLINICAL_TRIALS;
USE SCHEMA CURATED;

------------------------------------------------------------------------
-- SITE_PERFORMANCE: enrollment_rate, screen_fail_rate by site
------------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE SITE_PERFORMANCE
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    s.SITE_ID,
    s.SITE_NAME,
    s.HOSPITAL_NAME,
    s.CITY,
    s.COUNTRY,
    s.LATITUDE,
    s.LONGITUDE,
    s.PI_NAME,
    COUNT(DISTINCT e.ENROLLMENT_ID) AS TOTAL_ENROLLMENTS,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'ENROLLED' THEN e.ENROLLMENT_ID END) AS ACTIVE_ENROLLMENTS,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'SCREEN_FAILED' THEN e.ENROLLMENT_ID END) AS SCREEN_FAILURES,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'WITHDRAWN' THEN e.ENROLLMENT_ID END) AS WITHDRAWALS,
    ROUND(COUNT(DISTINCT CASE WHEN e.STATUS = 'ENROLLED' THEN e.ENROLLMENT_ID END)::FLOAT /
        NULLIF(COUNT(DISTINCT e.ENROLLMENT_ID), 0) * 100, 1) AS ENROLLMENT_RATE,
    ROUND(COUNT(DISTINCT CASE WHEN e.STATUS = 'SCREEN_FAILED' THEN e.ENROLLMENT_ID END)::FLOAT /
        NULLIF(COUNT(DISTINCT e.ENROLLMENT_ID), 0) * 100, 1) AS SCREEN_FAIL_RATE,
    COUNT(DISTINCT e.TRIAL_ID) AS TRIALS_AT_SITE,
    DATEDIFF('day', MIN(e.ENROLLMENT_DATE), CURRENT_DATE()) AS DAYS_ACTIVE,
    ROUND(COUNT(DISTINCT CASE WHEN e.STATUS = 'ENROLLED' THEN e.ENROLLMENT_ID END)::FLOAT /
        NULLIF(DATEDIFF('month', MIN(e.ENROLLMENT_DATE), CURRENT_DATE()), 0), 1) AS MONTHLY_ENROLLMENT_RATE
FROM RAW.SITES s
LEFT JOIN RAW.ENROLLMENTS e ON s.SITE_ID = e.SITE_ID
GROUP BY s.SITE_ID, s.SITE_NAME, s.HOSPITAL_NAME, s.CITY, s.COUNTRY,
         s.LATITUDE, s.LONGITUDE, s.PI_NAME;

------------------------------------------------------------------------
-- PATIENT_ELIGIBILITY: match patients to trial criteria with score
------------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE PATIENT_ELIGIBILITY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.SITE_ID,
    t.TRIAL_ID,
    t.TRIAL_NAME,
    t.THERAPEUTIC_AREA,
    COUNT(c.CRITERIA_ID) AS TOTAL_CRITERIA,
    SUM(CASE
        WHEN c.PARAMETER = 'AGE' AND DATEDIFF('year', p.DATE_OF_BIRTH, CURRENT_DATE()) BETWEEN COALESCE(c.MIN_VALUE, 0) AND COALESCE(c.MAX_VALUE, 999) THEN 1
        WHEN c.PARAMETER = 'BMI' AND p.BMI BETWEEN COALESCE(c.MIN_VALUE, 0) AND COALESCE(c.MAX_VALUE, 999) THEN 1
        WHEN c.PARAMETER = 'LDL' AND p.CHOLESTEROL_LEVEL >= COALESCE(c.MIN_VALUE, 0) THEN 1
        WHEN c.PARAMETER = 'CONSENT' THEN 1
        WHEN c.PARAMETER IN ('MALIGNANCY', 'PRIOR_THERAPY') THEN 1
        WHEN c.PARAMETER = 'SBP' THEN 1
        WHEN c.PARAMETER = 'HBA1C' AND p.DIABETES_STATUS IN ('Type 2', 'Pre-diabetic') THEN 1
        WHEN c.PARAMETER = 'EGFR' THEN 1
        WHEN c.PARAMETER = 'ALT' THEN 1
        ELSE 0
    END) AS CRITERIA_MET,
    ROUND(SUM(CASE
        WHEN c.PARAMETER = 'AGE' AND DATEDIFF('year', p.DATE_OF_BIRTH, CURRENT_DATE()) BETWEEN COALESCE(c.MIN_VALUE, 0) AND COALESCE(c.MAX_VALUE, 999) THEN 1
        WHEN c.PARAMETER = 'BMI' AND p.BMI BETWEEN COALESCE(c.MIN_VALUE, 0) AND COALESCE(c.MAX_VALUE, 999) THEN 1
        WHEN c.PARAMETER = 'LDL' AND p.CHOLESTEROL_LEVEL >= COALESCE(c.MIN_VALUE, 0) THEN 1
        WHEN c.PARAMETER = 'CONSENT' THEN 1
        WHEN c.PARAMETER IN ('MALIGNANCY', 'PRIOR_THERAPY') THEN 1
        WHEN c.PARAMETER = 'SBP' THEN 1
        WHEN c.PARAMETER = 'HBA1C' AND p.DIABETES_STATUS IN ('Type 2', 'Pre-diabetic') THEN 1
        WHEN c.PARAMETER = 'EGFR' THEN 1
        WHEN c.PARAMETER = 'ALT' THEN 1
        ELSE 0
    END)::FLOAT / NULLIF(COUNT(c.CRITERIA_ID), 0) * 100, 1) AS ELIGIBILITY_SCORE
FROM RAW.PATIENTS p
CROSS JOIN RAW.TRIALS t
LEFT JOIN RAW.ELIGIBILITY_CRITERIA c ON t.TRIAL_ID = c.TRIAL_ID
WHERE NOT EXISTS (
    SELECT 1 FROM RAW.ENROLLMENTS e
    WHERE e.PATIENT_ID = p.PATIENT_ID AND e.TRIAL_ID = t.TRIAL_ID
)
GROUP BY p.PATIENT_ID, p.FIRST_NAME, p.LAST_NAME, p.SITE_ID,
         t.TRIAL_ID, t.TRIAL_NAME, t.THERAPEUTIC_AREA
HAVING COUNT(c.CRITERIA_ID) > 0;

------------------------------------------------------------------------
-- ENROLLMENT_FORECAST_DAILY: daily enrollment counts for ML input
------------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE ENROLLMENT_FORECAST_DAILY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    e.TRIAL_ID,
    t.TRIAL_NAME,
    e.ENROLLMENT_DATE AS FORECAST_DATE,
    COUNT(*) AS DAILY_ENROLLMENTS,
    SUM(COUNT(*)) OVER (PARTITION BY e.TRIAL_ID ORDER BY e.ENROLLMENT_DATE) AS CUMULATIVE_ENROLLMENTS,
    t.TARGET_ENROLLMENT,
    ROUND(SUM(COUNT(*)) OVER (PARTITION BY e.TRIAL_ID ORDER BY e.ENROLLMENT_DATE)::FLOAT /
        NULLIF(t.TARGET_ENROLLMENT, 0) * 100, 2) AS PERCENT_TARGET
FROM RAW.ENROLLMENTS e
JOIN RAW.TRIALS t ON e.TRIAL_ID = t.TRIAL_ID
WHERE e.STATUS IN ('ENROLLED', 'COMPLETED')
GROUP BY e.TRIAL_ID, t.TRIAL_NAME, e.ENROLLMENT_DATE, t.TARGET_ENROLLMENT;
