------------------------------------------------------------------------
-- Clinical Trial Operations: Curated Layer (Dynamic Tables)
------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;
USE DATABASE HEALTHCARE_CLINICAL_TRIALS;
USE SCHEMA CURATED;

------------------------------------------------------------------------
-- SITE_PERFORMANCE: enrollment_rate, screen_fail_rate by site
------------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE SITE_PERFORMANCE
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    s.SITE_ID,
    s.SITE_NAME,
    s.HOSPITAL_NAME,
    s.CITY,
    s.COUNTRY,
    s.LATITUDE,
    s.LONGITUDE,
    s.PI_NAME,
    COUNT(DISTINCT e.ENROLLMENT_ID) AS TOTAL_ENROLLMENTS,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'ENROLLED' THEN e.ENROLLMENT_ID END) AS ACTIVE_ENROLLMENTS,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'SCREEN_FAILED' THEN e.ENROLLMENT_ID END) AS SCREEN_FAILURES,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'WITHDRAWN' THEN e.ENROLLMENT_ID END) AS WITHDRAWALS,
    ROUND(COUNT(DISTINCT CASE WHEN e.STATUS = 'ENROLLED' THEN e.ENROLLMENT_ID END)::FLOAT /
        NULLIF(COUNT(DISTINCT e.ENROLLMENT_ID), 0) * 100, 1) AS ENROLLMENT_RATE,
    ROUND(COUNT(DISTINCT CASE WHEN e.STATUS = 'SCREEN_FAILED' THEN e.ENROLLMENT_ID END)::FLOAT /
        NULLIF(COUNT(DISTINCT e.ENROLLMENT_ID), 0) * 100, 1) AS SCREEN_FAIL_RATE,
    COUNT(DISTINCT e.TRIAL_ID) AS TRIALS_AT_SITE,
    DATEDIFF('day', MIN(e.ENROLLMENT_DATE), CURRENT_DATE()) AS DAYS_ACTIVE,
    ROUND(COUNT(DISTINCT CASE WHEN e.STATUS = 'ENROLLED' THEN e.ENROLLMENT_ID END)::FLOAT /
        NULLIF(DATEDIFF('month', MIN(e.ENROLLMENT_DATE), CURRENT_DATE()), 0), 1) AS MONTHLY_ENROLLMENT_RATE
FROM RAW.SITES s
LEFT JOIN RAW.ENROLLMENTS e ON s.SITE_ID = e.SITE_ID
GROUP BY s.SITE_ID, s.SITE_NAME, s.HOSPITAL_NAME, s.CITY, s.COUNTRY,
         s.LATITUDE, s.LONGITUDE, s.PI_NAME;

------------------------------------------------------------------------
-- PATIENT_ELIGIBILITY: match patients to trial criteria with score
------------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE PATIENT_ELIGIBILITY
    TARGET_LAG = '5 minutes'
    WAREHOUSE = CORTEX
AS
WITH patient_trial_match AS (
    SELECT
        p.PATIENT_ID,
        p.FIRST_NAME,
        p.LAST_NAME,
        p.DATE_OF_BIRTH,
        p.GENDER,
        p.COUNTRY,
        p.CHRONIC_CONDITIONS,
        t.TRIAL_ID,
        t.TITLE AS TRIAL_TITLE,
        t.THERAPEUTIC_AREA,
        CASE
            WHEN p.CHRONIC_CONDITIONS LIKE '%Atrial Fibrillation%' AND t.TRIAL_ID IN ('CARDIO-PREVENT-301','CARDIO-AFIB-301') THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Anticoagulation%' AND t.TRIAL_ID = 'CARDIO-PREVENT-301' THEN 35
            WHEN p.CHRONIC_CONDITIONS LIKE '%Heart Failure%' AND t.TRIAL_ID = 'CARDIO-HF-201' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Hypertension%' AND t.TRIAL_ID IN ('CARDIO-HTN-201','CARDIO-PREVENT-301') THEN 20
            WHEN p.CHRONIC_CONDITIONS LIKE '%Diabetes%' AND t.TRIAL_ID IN ('ENDO-DM2-201','ENDO-OBS-301') THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Obesity%' AND t.TRIAL_ID = 'ENDO-OBS-301' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%COPD%' AND t.TRIAL_ID = 'RESP-COPD-301' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Asthma%' AND t.TRIAL_ID = 'RESP-ASTH-201' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Alzheimer%' AND t.TRIAL_ID = 'NEURO-AD-302' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Multiple Sclerosis%' AND t.TRIAL_ID = 'NEURO-MS-301' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Arthritis%' AND t.TRIAL_ID = 'IMMUNO-RA-202' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Psoriasis%' AND t.TRIAL_ID = 'IMMUNO-PSO-301' THEN 30
            WHEN p.CHRONIC_CONDITIONS LIKE '%Cancer%' AND t.THERAPEUTIC_AREA = 'Oncology' THEN 25
            WHEN p.CHRONIC_CONDITIONS LIKE '%Kidney%' AND t.TRIAL_ID = 'ENDO-DM2-201' THEN 20
            ELSE 5
        END
        + CASE WHEN DATEDIFF(YEAR, p.DATE_OF_BIRTH, CURRENT_DATE()) BETWEEN 40 AND 75 THEN 20 ELSE 10 END
        + CASE WHEN p.COUNTRY IN ('Singapore', 'Australia', 'Japan', 'South Korea') THEN 15 ELSE 10 END
        + CASE WHEN MOD(ABS(HASH(p.PATIENT_ID || t.TRIAL_ID)), 100) <= 30 THEN 20 ELSE 0 END
        AS ELIGIBILITY_SCORE
    FROM RAW.PATIENTS p
    CROSS JOIN (SELECT TRIAL_ID, TITLE, THERAPEUTIC_AREA FROM RAW.TRIALS WHERE STATUS = 'ENROLLING' LIMIT 10) t
)
SELECT
    ptm.PATIENT_ID,
    ptm.FIRST_NAME,
    ptm.LAST_NAME,
    ptm.DATE_OF_BIRTH,
    ptm.GENDER,
    ptm.COUNTRY,
    ptm.CHRONIC_CONDITIONS,
    ptm.TRIAL_ID,
    ptm.TRIAL_TITLE,
    ptm.THERAPEUTIC_AREA,
    LEAST(ptm.ELIGIBILITY_SCORE, 100) AS ELIGIBILITY_SCORE,
    CASE WHEN e.ENROLLMENT_ID IS NOT NULL THEN 'APPROACHED'
         ELSE 'NOT_APPROACHED'
    END AS APPROACH_STATUS
FROM patient_trial_match ptm
LEFT JOIN RAW.ENROLLMENTS e
     ON ptm.PATIENT_ID = e.PATIENT_ID AND ptm.TRIAL_ID = e.TRIAL_ID
WHERE ptm.ELIGIBILITY_SCORE >= 40;

------------------------------------------------------------------------
-- ENROLLMENT_FORECAST_DAILY: daily enrollment counts for ML input
------------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE ENROLLMENT_FORECAST_DAILY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    e.TRIAL_ID,
    t.TRIAL_NAME,
    e.ENROLLMENT_DATE AS FORECAST_DATE,
    COUNT(*) AS DAILY_ENROLLMENTS,
    SUM(COUNT(*)) OVER (PARTITION BY e.TRIAL_ID ORDER BY e.ENROLLMENT_DATE) AS CUMULATIVE_ENROLLMENTS,
    t.TARGET_ENROLLMENT,
    ROUND(SUM(COUNT(*)) OVER (PARTITION BY e.TRIAL_ID ORDER BY e.ENROLLMENT_DATE)::FLOAT /
        NULLIF(t.TARGET_ENROLLMENT, 0) * 100, 2) AS PERCENT_TARGET
FROM RAW.ENROLLMENTS e
JOIN RAW.TRIALS t ON e.TRIAL_ID = t.TRIAL_ID
WHERE e.STATUS IN ('ENROLLED', 'COMPLETED')
GROUP BY e.TRIAL_ID, t.TRIAL_NAME, e.ENROLLMENT_DATE, t.TARGET_ENROLLMENT;
