-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT site.ID AS ENTITY_ID, site.NAME AS ENTITY_NAME,
       site.REGION, site.CATEGORY, site.MONITORING_TIER, site.STATUS,
       site.ENROLLMENT_TARGET_90D,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.SCREENED_COUNT) AS SCREENED_COUNT,
       SUM(observation.ENROLLED_COUNT) AS ENROLLED_COUNT,
       SUM(observation.SIGNAL_COUNT) AS SIGNAL_COUNT,
       SUM(observation.CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(observation.CAPA_OPENED) AS CAPA_COUNT,
       SUM(observation.MONITORING_DUE) AS MONITORING_DUE,
       SUM(observation.MONITORING_COMPLETED) AS MONITORING_COMPLETED,
       100.0 * SUM(observation.ENROLLED_COUNT) / NULLIF(site.ENROLLMENT_TARGET_90D, 0) AS ENROLLMENT_VS_PLAN_PCT,
       100.0 * (SUM(observation.SCREENED_COUNT) - SUM(observation.ENROLLED_COUNT)) / NULLIF(SUM(observation.SCREENED_COUNT), 0) AS SCREEN_FAILURE_PCT,
       100.0 * SUM(observation.CONFIRMED_COUNT) / NULLIF(SUM(observation.SIGNAL_COUNT), 0) AS SIGNAL_CONFIRMATION_PCT,
       100.0 * SUM(observation.MONITORING_COMPLETED) / NULLIF(SUM(observation.MONITORING_DUE), 0) AS MONITORING_COMPLIANCE_PCT,
       AVG(observation.QUERY_RATE_PCT) AS AVG_QUERY_RATE_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.SITE_DAILY observation
JOIN RAW.SITES site ON site.ID = observation.ENTITY_ID
GROUP BY site.ID, site.NAME, site.REGION, site.CATEGORY, site.MONITORING_TIER, site.STATUS, site.ENROLLMENT_TARGET_90D;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(SCREENED_COUNT) AS SCREENED_COUNT, SUM(ENROLLED_COUNT) AS ENROLLED_COUNT,
       SUM(SIGNAL_COUNT) AS SIGNAL_COUNT, SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       100.0 * SUM(CONFIRMED_COUNT) / NULLIF(SUM(SIGNAL_COUNT), 0) AS SIGNAL_CONFIRMATION_PCT
FROM RAW.SITE_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.SIGNAL_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT SIGNAL_TYPE, SUM(SIGNAL_COUNT) AS SIGNAL_COUNT,
       SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(CAPA_OPENED) AS CAPA_COUNT,
       COUNT(DISTINCT ENTITY_ID) AS SITES_AFFECTED,
       100.0 * SUM(CONFIRMED_COUNT) / NULLIF(SUM(SIGNAL_COUNT), 0) AS SIGNAL_CONFIRMATION_PCT
FROM RAW.SITE_DAILY
WHERE SIGNAL_COUNT > 0
GROUP BY SIGNAL_TYPE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(SIGNAL_COUNT) AS SIGNALS, SUM(CONFIRMED_COUNT) AS CONFIRMED,
         SUM(CAPA_OPENED) AS CAPAS, SUM(SCREENED_COUNT) AS SCREENED, SUM(ENROLLED_COUNT) AS ENROLLED,
         SUM(MONITORING_DUE) AS MONITORING_DUE, SUM(MONITORING_COMPLETED) AS MONITORING_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.SITE_DAILY
), portfolio AS (SELECT COUNT(*) AS SITE_COUNT, SUM(ENROLLMENT_TARGET_90D) AS TARGET FROM RAW.SITES),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.ESSENTIAL_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Enrollment vs Plan' AS TITLE,
         100.0 * ENROLLED / NULLIF(TARGET, 0) AS VALUE_NUM, '%' AS UNIT FROM observations CROSS JOIN portfolio
  UNION ALL SELECT 2, 'Participants Enrolled', ENROLLED, '' FROM observations
  UNION ALL SELECT 3, 'Screen Failure Rate', 100.0 * (SCREENED - ENROLLED) / NULLIF(SCREENED, 0), '%' FROM observations
  UNION ALL SELECT 4, 'Signal Confirmation Rate', 100.0 * CONFIRMED / NULLIF(SIGNALS, 0), '%' FROM observations
  UNION ALL SELECT 5, 'Monitoring Signals', SIGNALS, '' FROM observations
  UNION ALL SELECT 6, 'Important Deviations', CONFIRMED, '' FROM observations
  UNION ALL SELECT 7, 'CAPAs Opened', CAPAS, '' FROM observations
  UNION ALL SELECT 8, 'Monitoring Visit Compliance', 100.0 * MONITORING_COMPLETED / NULLIF(MONITORING_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Sites Active', SITE_COUNT, '' FROM portfolio
  UNION ALL SELECT 10, 'Essential Document Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Essential Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.SIGNAL_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
