-- Important-deviation risk scoring and enrollment forecast over the synthetic snapshot.
-- Predicts P(confirmed important protocol deviation in the next 7 days) per site
-- and reports out-of-time holdout metrics; nothing is seeded as a prediction.
-- These are operational site-management scores, not clinical or safety predictions.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.DEVIATION_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, s.CATEGORY, s.MONITORING_TIER, s.YEARS_ACTIVE,
       r.QUERY_RATE_PCT, r.ENTRY_LAG_DAYS,
       AVG(r.QUERY_RATE_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS QUERY_RATE_7D,
       SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS CONFIRMED_30D,
       IFF(SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'DEVIATION', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.SITE_DAILY r JOIN RAW.SITES s ON s.ID = r.ENTITY_ID
-- Regional EDC outages are not site-driven, so they are excluded from training.
WHERE r.SIGNAL_TYPE <> 'Regional EDC outage';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.DEVIATION_TRAIN AS
SELECT CATEGORY, MONITORING_TIER, YEARS_ACTIVE, QUERY_RATE_PCT, ENTRY_LAG_DAYS, QUERY_RATE_7D, CONFIRMED_30D, LABEL
FROM ML.DEVIATION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.DEVIATION_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, MONITORING_TIER, YEARS_ACTIVE, QUERY_RATE_PCT, ENTRY_LAG_DAYS, QUERY_RATE_7D, CONFIRMED_30D, LABEL
FROM ML.DEVIATION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.DEVIATION_RISK_MODEL(
  INPUT_DATA => TABLE(ML.DEVIATION_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.DEVIATION_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.DEVIATION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'MONITORING_TIER', MONITORING_TIER, 'YEARS_ACTIVE', YEARS_ACTIVE,
           'QUERY_RATE_PCT', QUERY_RATE_PCT, 'ENTRY_LAG_DAYS', ENTRY_LAG_DAYS,
           'QUERY_RATE_7D', QUERY_RATE_7D, 'CONFIRMED_30D', CONFIRMED_30D)):probability:DEVIATION::FLOAT AS P
  FROM ML.DEVIATION_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'DEVIATION', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'DEVIATION', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'DEVIATION', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'DEVIATION', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per site (label unknown, so excluded from features).
CREATE TABLE ML.DEVIATION_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.DEVIATION_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.DEVIATION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'MONITORING_TIER', MONITORING_TIER, 'YEARS_ACTIVE', YEARS_ACTIVE,
           'QUERY_RATE_PCT', QUERY_RATE_PCT, 'ENTRY_LAG_DAYS', ENTRY_LAG_DAYS,
           'QUERY_RATE_7D', QUERY_RATE_7D, 'CONFIRMED_30D', CONFIRMED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:DEVIATION::FLOAT, 4) AS DEVIATION_PROB_7D,
       CASE WHEN P:probability:DEVIATION::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:DEVIATION::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Portfolio-wide enrollment forecast (14 days) from the daily series, for recruitment planning.
CREATE VIEW ML.DAILY_ENROLLMENT AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(ENROLLED_COUNT)::FLOAT AS ENROLLED_COUNT
FROM RAW.SITE_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.ENROLLMENT_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_ENROLLMENT),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'ENROLLED_COUNT'
);

CREATE TABLE ML.ENROLLMENT_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS ENROLLED_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.ENROLLMENT_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
